### ISSUE TITLE
save_mysql_passwd is broken for mysql 5.7

### ISSUE THREAD

**Issue by psrpardhasaradhi** [Appdynamics/HA-toolkit#78] opened 2017-11-28 12:05 UTC
When HA toolkit detects the mysql_config_editor, it does not save obfuscated password to db/.rootpw.obf.  password.sh is not yet ready to read the password saved by mysql_config_editor.

A workaround is to skip checking for $APPD_ROOT/db/bin/mysql_config_editor altogether and always call save_mysql_passwd $APPD_ROOT

But with this workaround, what happens with mysqlclient.sh is that you would see a warning that is not handled. This happens with mysql 5.7 and not 5.5. 

**Warning: Using a password on the command line interface can be insecure.**

Thus, when the init scripts check for the active/passive mode, the script mysqlclient.sh returns "[Warning]" at the start of the variable, so the checks fail. Eg the variable is set to "[Warning]\nactive" instead of "active"

https://dev.mysql.com/doc/refman/5.7/en/mysql-config-editor.html
https://stackoverflow.com/questions/20751352/suppress-warning-messages-using-mysql-from-within-terminal-but-password-written

**Note:** Version 3.26 works without any changes to the scripts. mysqlclient.sh uses .mylogin.cnf and logs into the database just fine and services could also be installed.

@rnav1234

**Comment by cmayer68** [comment] 2018-01-25 23:12
not sure what the problem is.   if you are running mysql 5.7, then the HA toolkit must have a valid mylogin.cnf, which needs to be pointed at by MYSQL_TEST_LOGIN_FILE.  mysqlclient gets this.

--curt

**Comment by rnav1234** [comment] 2018-02-20 22:08
I believe this issue has been fixed with 3.28.4

**Closed by rnav1234** 2018-02-20 22:08 UTC
Labels: bug
