### ISSUE TITLE
replicate.sh -f doesn't work for the first time on newer version of ubuntu

### ISSUE THREAD

**Issue by shannonxuappd** [Appdynamics/HA-toolkit#64] opened 2017-04-25 18:09 UTC
Hi Curt,
When we used newer version of AWS ubuntu images(ami-a58d0dc5, Linux ip-172-31-6-215 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux) for automating HA setup. replicate.sh with -f option doesn't work for the first time, it will hang at 'start Secondary database'. Secondary's db cannot be started manually as well.
But if executing 'replicate.sh -f' command again on primary node, it will succeed. As I verified, this only happens for the first time when executing 'replicate.sh -f'. We have to roll back to an older ubuntu AMI image to avoid this. I am not sure if this is a bug related to ubuntu versions.

**Comment by rnav1234** [comment] 2019-06-04 03:57
Duplicate of #103

**Closed by rnav1234** 2019-06-04 03:57 UTC
